name: cd
on:
  push:
    branches:
      - main
      - next

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main

      - name: Configure CI Git User
        run: |
          git config --global user.name 'guiseek'
          git config --global user.email 'guiseek@gmail.com'
          git remote set-url origin https://guiseek:$GITHUB_TOKEN@github.com/guiseek/nxgs

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Link package
        run: npx nx run-many -t build --projects devkit,release --skip-nx-cache
          npm link dist/packages/release
          npm ls @nxgs/release

      - name: Print versions
        run: |
          echo "node: \t $(node -v)"
          echo "npm: \t $(npm -v)"
          echo "$(npx nx --version)"

      - name: Release
        run: |
          npx nx-cloud record -- nx format:check
          npx nx affected --target=release --parallel=3

        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
