name: ci

on:
  push:
    branches:
      - main
  pull_request:

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
    with:
      main-branch-name: main
      number-of-agents: 3
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.1
    with:
      number-of-agents: 3

  publish:
    name: Publish
    if: ${{ github.repository_owner == 'guiseek' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    needs:
      - main
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          check-latest: true
      - name: Install dependencies
        run: npm ci
      - name: Affected
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx nx affected --target=publish --parallel=3 --dry-run
          else
            npx nx affected --target=publish --parallel=3
          fi

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
